### PR TITLE
[enrich-meetup] Refactor logic to enrich items

### PR DESCRIPTION
**Pull request by valeriocos**
This code changes the logic to enrich items. Now, raw items are enriched on the fly together with enriched rsvps and comments. Tests have been modified accordingly.

### CODE REVIEW

**Review by acs — APPROVED** [review]
LGTM

**Comment by valeriocos** [comment]
This PR should solve also the issue https://github.com/chaoss/grimoirelab-elk/issues/322

**Review by sduenas — COMMENTED** [review]
Everything looks good me. Though, I would add some message when the process finishes about the number of items processed - in the same way there's an error saying which Meetup items were lost -.

**Comment by valeriocos** [comment]
I add a message about the number of items processed (when no items are lost). WRT the other message you comment, this should be already handled by ELK

**Review by sduenas — APPROVED** [review]

**Pull request merged**
