### PR TITLE
[ELK] Support ODFE

### PR DESCRIPTION
**Pull request by valeriocos**
This code provides some fixes to support ODFE 1.2.0/elasticsearch 7.2.0.
This PR should be reviewed together with https://github.com/chaoss/grimoirelab-sirmordred/pull/362

### CODE REVIEW

**Review by sduenas — COMMENTED** [review]
LGTM but it will worth that other person also reviews this. I also wonder why mappings are deleted and not used anymore.

**Comment by valeriocos** [comment]
The deletion at https://github.com/chaoss/grimoirelab-elk/pull/716/files#diff-f7f4f8e73e7f8b04b43608dfaf3712ffL321 is due to the fact that code was for ES 2 and 5 (which is not supported anymore).

The deletion at https://github.com/chaoss/grimoirelab-elk/pull/716/files#diff-ea21b6959f1e04a43327ff62568ebf7bL483 is due to the fact that we don't use custom analyzers. I double-checked with @alpgarcia and we didn't find any reference of custom analyzers in use.

**Comment by sduenas** [comment]
> The deletion at https://github.com/chaoss/grimoirelab-elk/pull/716/files#diff-f7f4f8e73e7f8b04b43608dfaf3712ffL321 is due to the fact that code was for ES 2 and 5 (which is not supported anymore).
> 
> The deletion at https://github.com/chaoss/grimoirelab-elk/pull/716/files#diff-ea21b6959f1e04a43327ff62568ebf7bL483 is due to the fact that we don't use custom analyzers. I double-checked with @alpgarcia and we didn't find any reference of custom analyzers in use.

Ok! Should someone else check this PR?

**Comment by valeriocos** [comment]
Maybe @jjmerchante or @jsmanrique

**Pull request merged**
