### PR TITLE
[schemas] Fix GitLab CSVs to add missing columns

### PR DESCRIPTION
**Pull request by alpgarcia**
Add `aggregatable` and `description` fields to GitLab CSVs.

### CODE REVIEW

**Review by sduenas — CHANGES_REQUESTED** [review]
You need to add `time_to_merge_days`. This field was added in #525 .

**Comment by alpgarcia** [comment]
@sduenas I think `time_to_merge_days` is not added to the enriched item in that PR, or at least I don't see where.

**Comment by valeriocos** [comment]
`time_to_merge_days` is a variable and it is not added to the enriched items. `time_to_close_days` is the attribute added to the enriched item, more info at: https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/gitlab.py#L273

**Comment by sduenas** [comment]
Ok. I thought it was part of the enriched items. You can merge this PR.

**Review by sduenas — APPROVED** [review]

**Pull request merged**
