### PR TITLE
[tests] Allow testing with latest grimoirelab component versions

### PR DESCRIPTION
**Pull request by valeriocos**
This code allows to execute the tests using the latest versionsof the grimoirelab components required by E LK, thus simplyfing the testing of features that involve more components. The components are:
- grimoirelab-sortinghat
- grimoirelab-toolkit
- grimoirelab-cereslib
- grimoirelab-kingarthur
- grimoirelab-perceval
- grimoirelab-perceval-mozilla
- grimoirelab-perceval-opnfv
- grimoirelab-perceval-puppet

### CODE REVIEW

**Comment by valeriocos** [comment]
This PR includes also PR #378. The inclusion was needed to make the tests passing

**Comment by filmaj** [comment]
+1 to this PR, this fixes the updates to changes in SortingHat. Without merging this PR, Mordred tests fail, FYI.

(cc @jgbarah)

**Review by acs — CHANGES_REQUESTED** [review]
LGTM, but there are two different things in this PR: one for using the latest versions in travis, and the other the fix for SH exception. Could you break down the PR in two? Thanks @valeriocos

**Comment by valeriocos** [comment]
Sure @acs , I joined the two prs to make the tests passing. Please have a look at the new version

**Review by acs — APPROVED** [review]

**Pull request merged**
