### PR TITLE
Fix mapping and bulk URL for ES 8.X and OS 2.X

### PR DESCRIPTION
**Pull request by Rafaeltheraven**
The way support for ES 7.X and OS 1.X was originally implemented meant that any major version that was not EXACTLY 7/1 would revert to old behavior. This is obviously wrong and simply changing this check to allow versions >= 7/1 seems to just work (at least in the context of using mordred to import git data from perceval).

I can not guarantee that everything works, and I know that at least kibash still needs some work as discussed here. But in any case, the check was wrong, and this PR should at least fix that.

:edit: Recreated this PR as I messed up what branch I used as the source for this PR and the old one got unclean.

### CODE REVIEW

**Comment by jjmerchante** [comment]
Thanks for your patch. Could you rebase the PR (cause the tests are failing) and squash the commits?

I also see some unrelated code to the PR inside the `.github/workflows` directory.

Thank you

**Comment by Rafaeltheraven** [comment]
My apologies, the project for which these fixes were originally made ended so I got distracted, I've cleaned up the PR now and squashed everything into 1 commit.

**Comment by jjmerchante** [comment]
LGTM

Can you please add a changelog like in the other pull request?

**Comment by zhquan** [comment]
Thank you very much for your contribution

**Pull request merged**
