### PR TITLE
[git] Add schema column for raw/calculated

### PR DESCRIPTION
**Pull request by GeorgLink**
Provide additional information where data in the schema originally comes
from and what was tool was used to enrich it.

Sort fields alphabetically.

This is only for the `git` index. I would open additional PRs for other indexes as well.

### CODE REVIEW

**Comment by GeorgLink** [comment]
Force pushed updated commit message with my DCO sign-off

**Comment by zhquan** [comment]
@GeorgLink thanks for the PR

If this PR is only for git, could you add `[git] .....` on the title?

**Comment by GeorgLink** [comment]
Done

**Comment by zhquan** [comment]
Sorry I was not clear, I mean the title of the commit message

**Comment by GeorgLink** [comment]
Done, this time I updated the commit title 💯

**Comment by zhquan** [comment]
@GeorgLink the last thing.
Could you rebase it and I will merge it. Thanks.
```
This branch is 1 commit ahead, 2 commits behind master.
```

**Comment by GeorgLink** [comment]
How does this look to you?

**Review by zhquan — APPROVED** [review]
LGTM

**Pull request merged**
