### PR TITLE
[enrich] Remove emails from all enriched indexes

### PR DESCRIPTION
**Pull request by acs**
Emails were detected in git, github, jira and mbox. This commit
removes all the fields including emails.

### CODE REVIEW

**Comment by jgbarah** [comment]
> Some of the fields with emails are included in the CSV files which define the fields needed by the panels:

AFAIK, the CSV files include *all* fields in the current indexes, not only those used by the panels. Please check with @alpgarcia and @dicortazar.

**Review by jgbarah — COMMENTED** [review]
Shoudln't it better to do it the other way around? I mean, checking all fields that have not a real reason to be in the index, and then remove them (not only those with email addresses).

Obviously, just a comment. maybe could just be the origin for a new issue, while this pr is accepted.

**Comment by acs** [comment]
> Shoudln't it better to do it the other way around? I mean, checking all fields that have not a real reason to be in the index, and then remove them (not only those with email addresses).

Yes, but this is another issue that should be addressed in other ticket.

**Comment by acs** [comment]
> AFAIK, the CSV files include all fields in the current indexes, not only those used by the panels. Please check with @alpgarcia and @dicortazar.

Yes, you are right. The fields in the CSV were the fields that appeared in the mapping of enriched indexes, not the fields used by panels.

**Comment by valeriocos** [comment]
I guess the best solution is to create some samples for the enriched backends modified by this PR and try them on blue5, to be sure that no panel will get broken. 
The sample indexes are in the process of being created, then they will be uploaded to blue5.

**Comment by valeriocos** [comment]
The PR doesn't break the panels.
Should the csv files being updated to reflect the new attributes in the enriched indexes?

**Comment by acs** [comment]
> Should the csv files being updated to reflect the new attributes in the enriched indexes?

Yes!

**Review by valeriocos — COMMENTED** [review]
LGTM

**Pull request merged**
