### PR TITLE
Add raw-calculated fields for more schema objects

### PR DESCRIPTION
**Pull request by GeorgLink**
Replaces #1070 - fixes DCO-sign-off by co-authoring the commit.

Original message:

> Related to https://github.com/chaoss/grimoirelab-elk/pull/1023
>
> I took all the rest of the updated schema and put it into the files here. The major addition is a new "Raw/Calculated" field for the updated files :)

Co-authored-by: Matt Cantu Snell <msnell@unomaha.edu>

### CODE REVIEW

**Comment by sduenas** [comment]
Would you mind to rebase this PR?

**Comment by GeorgLink** [comment]
Sure, how does this look?

**Review by sduenas — COMMENTED** [review]
Can you add an empty new line at the end of all files?

**Comment by GeorgLink** [comment]
Empty lines are added 👍

**Comment by GeorgLink** [comment]
Is this ready to be merged now?

**Pull request merged**
