### PR TITLE
update github_events #951

### PR DESCRIPTION
**Pull request by rohanreddych**
Signed-off-by: rohan reddy <rohan.ch.reddy@gmail.com>

### CODE REVIEW

**Comment by rohanreddych** [comment]
@sduenas i think you can merge this now?

**Review by sduenas — CHANGES_REQUESTED** [review]
Thanks. You didn't have to open a new PR, you could have done in the same one. You can amend your commits and push them again with the `--force` flag.

You should improve your commit message. As I said, please check the contribution section where we explain how to create a good commit message. Thanks!

**Review by sduenas — CHANGES_REQUESTED** [review]
This is better but the first line should be `Fix missing values in github event schema`. Add then a body like `Aggregatable columns didn't have a boolean value. This commit resolves #951`.

**Comment by rohanreddych** [comment]
@sduenas can you merge this ?

**Review by sduenas — CHANGES_REQUESTED** [review]
The commit message is wrong. It should be:

```
[schema] Fix missing values in github event schema.

Aggregatable column didn't have a boolean value.

This commit resolves #951
```

**Comment by rohanreddych** [comment]
> The commit message is wrong. It should be:
> 
> ```
> [schema] Fix missing values in github event schema.
> 
> Aggregatable column didn't have a boolean value.
> 
> This commit resolves #951
> ```

Will follow this format in the future.

**Comment by sduenas** [comment]
> > The commit message is wrong. It should be:
> > ```
> > [schema] Fix missing values in github event schema.
> > 
> > Aggregatable column didn't have a boolean value.
> > 
> > This commit resolves #951
> > ```
> 
> Will follow this format in the future.

Thanks. I also made a mistake with the format because I was cutting and pasting. The title of the commit doesn't have a period. For this time is ok.

**Comment by sduenas** [comment]
Merged.

**Pull request closed without merging**
