### PR TITLE
[ocean][crates] Avoid dynamic mapping for features field which has hundrends of different keys

### PR DESCRIPTION
**Pull request by acs**
This fixes the error

`2018-02-08 16:36:53,032 - grimoire_elk.elk.elastic - ERROR - Failed to insert data to ES: {'reason': 'Limit of total fields [1000] in index [crates_mozilla_171205_1] has been exceeded', 'type': 'illegal_argument_exception'}
`

### CODE REVIEW

**Comment by valeriocos** [comment]
Should we do something similar for version_downloads_data?

**Comment by acs** [comment]
Hmmm, we have no issues with `version_downloads_data`. Why are you afraid of it?

**Comment by valeriocos** [comment]
version_downloads_data and versions_data have similar structures. However we can improve the mappings when the error pops up

**Review by valeriocos — APPROVED** [review]
LGTM

**Comment by acs** [comment]
Already covered by https://github.com/chaoss/grimoirelab-elk/commit/c59c316c95d145a77d60abcbffef4e9c4c93b16d

Closing this PR without merging!

**Pull request closed without merging**
