### PR TITLE
[mordred] Add script to generate new JSON format files for project

### PR DESCRIPTION
**Pull request by canasdiaz**
Add script to generate the two JSON files we use now both for projects hierarchy and project-repos definition.

### CODE REVIEW

**Comment by sanacl** [comment]
Guys ( @acs, @dpose ), I would like both of you to review the code. Thank you!

**Review by jgbarah — COMMENTED** [review]
Instead of options designed in a way that you must run the script twice for doing the most usual think that the script is going to do (producing the two files), you better design it in a way that you can run it at once. A little tweak, for example, could help. Consider this shell command interface:

```
eclipse2bitergia.py -f eclipse.json -h hierarchy.json -p projects.json
```

If you only need one of them (-h or -p), just include only one of them.

This way, operation is simpler (you only need to call it once), and performance too (if reading the eclipse.json file takes a while, because it is long, you only need to read it once).

Besides, I didn't look at the source code, so maybe you already did this. But it is better if you can build it so that there is a function that mimics the shell command API, and that's the only thing that the main program does. That way, if in the future you want to integrate the code in a script, you just call that function instead of the command line.

In this specific case, since the function is dealing with JSON documents, there could be two levels: one with exactly the command line API (a function using file names as parameters), and a lower level accepting Python dictionaries as arguments, so that conversion to/from JSON (or YAML, or whatever) can be done elsewhere.

**Comment by sanacl** [comment]
Changed.

```
luis@hogaza ~/repos/my-forks/GrimoireELK/mordred/utils/json ±new_json_formatters⚡ » python3 eclipse2bitergia.py -h
usage: eclipse2bitergia.py -f <input_file> -y <hierarchy_file> -p <projects_file>

optional arguments:
  -h, --help            show this help message and exit
  -f INPUT_FILE, --input_file INPUT_FILE
                        Input file
  -y HIERARCHY_FILE, --hierarchy HIERARCHY_FILE
                        Output file for hierarchy
  -p PROJECTS_FILE, --projects PROJECTS_FILE
                        Output file for projects

```

**Review by jgbarah — APPROVED** [review]
Looks ok to me now!

**Comment by dpose** [comment]
It looks good to me too.
I'll test it as soon as I can to give more feedback.

**Comment by sanacl** [comment]
@acs ??

**Comment by acs** [comment]
@sanacl I am a bit out if context in this script. It is pretty simple so if it is ok for you, it is good for me also. For me it is a bit strange to generate several files at the same time using command line params, but if the goal of this script is that, it is ok.

**Pull request merged**
