### PR TITLE
Add missing status to Kitsune/SUMO index

### LINKED ISSUE #58: Add missing status to Kitsune/Sumo index
I've learned there are several ways a question can be "closed". Some of them are solved by the person who posted the question, some of them are closed by a user with privileges and some of them are archived after some months (it seems after 6 months).

We need to know when a question reaches that last stage and when.

So if feasible, please add these new fields to the enriched index:
 * closed_at: the time when the question was archived, closed, or solved
 * status: open, closed, archived, solved

### PR DESCRIPTION
**Pull request by jjmerchante**
There is a new field in the enriched index, `status`, which contains the current status of the question. The status could be `solved`, `archived`, `locked`, or `open`.

Fixes https://github.com/bitergia-analytics/bitergia-analytics/issues/58

### CODE REVIEW

**Comment by vchrombie** [comment]
Hi @jjmerchante, 

Would it be helpful to also update the schema to reflect this new field? I understand there’s a lot of pending work with schemas, but it might streamline understanding and usage, even if it’s one step at a time.

What are your thoughts on this?

**Comment by jjmerchante** [comment]
@vchrombie Yes, it is important for users. I created the full schema for Kitsune because it was missing.

**Review by sduenas — APPROVED** [review]
LGTM

**Review by sduenas — APPROVED** [review]
LGTM

**Pull request merged**
