### PR TITLE
[elk] Add option to fetch from selected branches

### LINKED ISSUE #642: Add option to fetch from selected branches
Currently, we can pass which category of items to be fetched from backends but the option doesn't exist for selection of branches.

@valeriocos Please let me know if I could open a PR for this (as I've worked on the changes locally). Thanks!

### PR DESCRIPTION
**Pull request by inishchith**
Fixes: #642 

@jgbarah @valeriocos Please do have a look, let me know if any changes required.

Thanks!

TODO:

- [ ] Add tests (if needed)
- [x] Update docstrings

Signed-off-by: inishchith <inishchith@gmail.com>

### CODE REVIEW

**Comment by valeriocos** [comment]
Thank you @inishchith for the PR, do you plan to add tests? I can have a look at the code and help you with this.

**Comment by inishchith** [comment]
@valeriocos I'll add the tests and ping you back.

Thanks!

**Comment by inishchith** [comment]
@valeriocos Sorry, I'm not sure if tests could be added as we do not have tests covering the [`ocean_backend.feed()`](https://github.com/chaoss/grimoirelab-elk/blob/8f5661ca22614dfded9d1bf237e65822b4bd923b/grimoire_elk/raw/elastic.py#L157) method. Please do correct me in case I missed something.

**Comment by valeriocos** [comment]
No worries, @inishchith I'll have a look and see if we can add some tests

**Comment by valeriocos** [comment]
It isn't straightforward to add tests since the code should be refactored.

**Review by valeriocos — APPROVED** [review]
LGTM! Thanks @inishchith

**Comment by valeriocos** [comment]
@sduenas I tested the PR and it works fine.

The change is similar to the one to include the `filter-classified` param (https://github.com/chaoss/grimoirelab-elk/commit/210e877b5419d11487278547bb592ae2f7138e81), so we shouldn't have surprises.

Tests cannot be easily added because the code should be refactored. If you agree we can give it a try otherwise the PR can be accepted as it is.

**Review by sduenas — APPROVED** [review]
LGTM. Let's merge it.

**Pull request merged**
