### PR TITLE
[graal] Add support of Graal's CoCom Backend to ELK

### PR DESCRIPTION
**Pull request by inishchith**
Address: https://github.com/inishchith/gsoc-graal/issues/8

**TODO:**
- [x] Add tests
- [ ] Update docstrings
- [ ] Update commit description

**NOTE:**
- The failing test is due to `Graal` module not being a part of `requirements.txt`(dependencies) and is a part of this PR just to check the coverage of new additions.

Signed-off-by: inishchith <inishchith@gmail.com>

### CODE REVIEW

**Comment by valeriocos** [comment]
As discussed at: https://github.com/inishchith/gsoc-graal/issues/11#issuecomment-507166421, please find below a proposal to extract modules from a file_path. The method `extract_modules` could be called in the [get_rich_item](https://github.com/chaoss/grimoirelab-elk/pull/651/files#diff-24d429520eb5fff2de2d44406c4d2eebR63), and the output stored in the attribute `modules` (or any other one) as follows: `eitem['modules'] = self.extract_modules(file_path)`

```
def extract_modules(file_path):

    path_chunks = file_path.split('/')

    modules = []
    for idx, p in enumerate(path_chunks):
        sub_path = '/'.join(path_chunks[:idx])

        if sub_path:
            modules.append(sub_path)

    return modules
```

WDYT @inishchith ?

**Comment by inishchith** [comment]
@valeriocos Thanks for elaborating on the idea. 
I'll update the PR and start working on the `module-level` idea.

Thanks!

**Comment by inishchith** [comment]
@valeriocos i've added some tests.
I'm not sure why the `coveralls` task reports aren't displayed. Can you please have a look?

**Comment by inishchith** [comment]
closing in reference to #664

**Pull request closed without merging**
