### PR TITLE
[enriched-gerrit] Handle missing user info

### PR DESCRIPTION
**Pull request by valeriocos**
This code handles missing user info such as owner, approvers and reviewers.

Test data have been modified accordingly.

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Can we marge this (#742) or that (#741) this is quite important for us, we're trying to avoid maintaining patched versions, so we're trying to upstream all bugs and fixes.

**Comment by valeriocos** [comment]
I asked for an internal review but yesterday was bank holiday in Spain. I guess between today or tomorrow the PR will be merged.

**Comment by lukaszgryglicki** [comment]
Great, I'll build a new base image then, hopefully, there will be no internal sub-projects conflicts (last time ELK and Perceval or Sorting Hat both required the same python library, but conflicting versions).

**Review by sduenas — APPROVED** [review]
LGTM

**Pull request merged**
