### PR TITLE
[doc] Update readme for secure elasticsearch

### PR DESCRIPTION
**Pull request by snack0verflow**
Added some instruction for secure elasticsearch and docker users.

### CODE REVIEW

**Review by valeriocos — COMMENTED** [review]
Thank you for the PR @snack0verflow !
Quick question, why the example in the third entry (populate the database ..) is different from the example in the second entry (create the databases ..)? It wouldn't be easy to have something like the examples below or I'm missing something?
- `docker exec -it <container id> mysql -u root -e "create database test_sh"` (for the second entry)
- `docker exec -it <container id> mysql -u root test_projects < tests/test_projects.sql"` (for the third entry)

**Comment by snack0verflow** [comment]
@valeriocos Thanks for pointing this out, the -t option is for TTY input which doesn't work while populating the database. I checked again and I think we can get rid of -t from both the cases.

**Comment by valeriocos** [comment]
thanks @snack0verflow for the quick reply!

**Comment by snack0verflow** [comment]
@valeriocos Why did the coverage decrease?

**Comment by valeriocos** [comment]
is your branch in sync with the master one?

**Review by valeriocos — APPROVED** [review]
LGTM, thanks @snack0verflow

**Pull request merged**
