### PR TITLE
Added test method for Area of Code in test_git.py

### PR DESCRIPTION
**Pull request by kshitij3199**
Test Method for Area of Code has been added in test_git.py file.

The main reason for doing so was to increase the coverage of git.py file. Which has been increased from 44% to 49% by adding this test.

Signed-off-by: Kshitij Gupta <kgupta3199@gmail.com>

### CODE REVIEW

**Comment by valeriocos** [comment]
Hi @kshitij3199 , the PR was perfect, it was just needed to fix the flake8 errors.
Why did you close it?

**Comment by kshitij3199** [comment]
@valeriocos , 
When I will correct flake8 error, it will show 2 commit in PR. So I thought of rebasing and making a new PR

**Comment by vchrombie** [comment]
Hi @kshitij3199 
> When I will correct flake8 error, it will show 2 commit in PR. So I thought of rebasing and making a new PR

That's fine, you can squash them and send in the same PR if you are ok with it.

**Comment by kshitij3199** [comment]
Thank you @vchrombie , I got your point.
I am new to squashing and all, and I am learning them.

**Comment by vchrombie** [comment]
> I am new to squashing and all, and I am learning them.

That's nice. I can help if you are stuck. Let's see from next PRs. :slightly_smiling_face:

**Comment by kshitij3199** [comment]
Thanks @vchrombie , 
I think by a healthy discussion we both can learn more.

**Comment by valeriocos** [comment]
Please @kshitij3199 try to do the following in this PR:

- create a new commit in the branch `aoc8`
- `git rebase -i HEAD~2`. This command will open a new editor with the following shape
```
pick <hash-1> commit title1
pick <hash-2> commit title2
```
- change the last `pick` with `f` to squash the 2 commits without keeping the message of `hash-2`

```
pick <hash-1> commit title1
f <hash-2> commit title2
```
- save and exit (Ctrl+O to save, and Ctrl+X to exit)
- `git log --oneline` to see that `hash-2` doesn't appear anymore
- `git show` to see that the changes of `hash-2` have been merged to `hash-1`
-  git push https://github.com/kshitij3199/grimoirelab-elk -f to update the PR (assuming that you are in `aoc8` branch).
- check in github that your PR has changed

Hope this helps

**Pull request closed without merging**
