### PR TITLE
[arthur] Fix params parsing for arthur tasks

### PR DESCRIPTION
**Pull request by acs**
All perceval backends are now supported in arthur except the ones provided by perceval-mozilla/opnfv/puppet because and problem installing their pip packages with arthur.

### CODE REVIEW

**Review by valeriocos — COMMENTED** [review]
should we provide some tests for this code?

**Comment by acs** [comment]
I have doubts about adding tests to this code. Probably yes. But this code is working against several pieces (arthur, config from mordred ...) so I am not really sure. But it is critical code that joins arthur and mordred so ... yes, let's add tests! I will do that. Thanks @valeriocos! I will update the PR. Also, we need to think about the doc related to it. But the doc for all this params is in perceval already.

**Comment by acs** [comment]
@valeriocos tests added for all data sources! Could you review them? If all is ok, please merge directly this PR! Thanks :+1:

**Comment by valeriocos** [comment]
@acs, please fix the flake8 errors

**Comment by acs** [comment]
flake8 issues fixed!

**Comment by valeriocos** [comment]
LGTM

**Pull request merged**
