### PR TITLE
Remove deprecated Kibana panel JSON files

### PR DESCRIPTION
**Pull request by dicortazar**
The new repository for panels is available at
https://github.com/grimoirelab/panels

### CODE REVIEW

**Comment by acs** [comment]
Hmmm, there are panels in this directory for Maniphest that are what we are using in our dogfooding. But we are not using it nowdays. @sanacl what do you think? Probably we can remove them and if needed, retrieve them from git history.

**Comment by jgbarah** [comment]
Assigned to @sanacl so that he (hopefully) sees this...

**Comment by dicortazar** [comment]
Comments?

**Comment by acs** [comment]
@dicortazar we are at the same point. In this directory for example we have the panels we created for phabricator that we use to track our internal activity. We need to review what it is here and to decide what to do.

**Comment by dicortazar** [comment]
Hey, why don't we migrate those panels to the panels repo? :)

And then remove those from here ;)...

**Comment by acs** [comment]
Sure, but probably those panels will need some love before adding them to panels repository. But it is the way to go!

**Comment by sanacl** [comment]
I would just remove the directory

**Comment by dicortazar** [comment]
This PR does that.

**Comment by acs** [comment]
LGTM. Ok, let's move all this stuff to attic! Thanks guys!

**Pull request merged**
