### PR TITLE
[elk] Add repo labels support

### PR DESCRIPTION
**Pull request by valeriocos**
This PR includes the method `extract_repo_labels`, which allows to collect the repo labels defined in the projects.json in the following way: https://github.com/chaoss/grimoirelab-perceval --labels=[collection]). It is
worth noting that this method hides the labels info to the rest of ELK in order to avoid breaking existing functionalities.
elk.py, enrichers and tests have been updated accordingly.

### CODE REVIEW

**Comment by valeriocos** [comment]
This PR should be reviewed with https://github.com/chaoss/grimoirelab-sirmordred/pull/302. Schema/CSV files will be updated once the PR is positively reviewed.

**Review by sduenas — CHANGES_REQUESTED** [review]
The PR looks OK but you have to add the new field to the CSV files.

**Comment by valeriocos** [comment]
Descriptions added, please @sduenas review it

**Review by sduenas — APPROVED** [review]
LGTM

**Pull request merged**
