### PR TITLE
[aoc] Replace message commit with first 80 chars

### PR DESCRIPTION
**Pull request by valeriocos**
This code replaces the content of commit messages with empty str, in order to limit the size of enriched indexes.

### CODE REVIEW

**Review by sduenas — COMMENTED** [review]
I think this is necessary due to indexes grow fast with repositories which have long message commits (i.e Eclipse).

A better solution would be to replace the message by the summary of the commit (first line of a commit) but right now this might work.

What do you think @acs?

**Comment by jgbarah** [comment]
If it is not very difficult, having the first line (or even the first 80 chars, or up to the first new line, whatever is first) would be much better. This would for allow to have panels or reports with the summary commits, which may be very valuable.

**Comment by acs** [comment]
I think your proposal of conserving the first line is a better option. Maybe @valeriocos could adapt the commit to this idea.

**Comment by valeriocos** [comment]
I have just modified the PR according to @jgbarah suggestion, now only the first 80 chars are kept.

**Review by sduenas — APPROVED** [review]
LGTM

**Pull request merged**
