### PR TITLE
[enriched-git] Add weekday and hour info to enriched commits

### PR DESCRIPTION
**Pull request by valeriocos**
This code enhances the enriched items derived from Git commits by including the day of the week and the hour of the day when the commit was authored and committed.

Tests have been added accordingly.
Schema has been updated.

Signed-off-by: Valerio Cosentino <valcos@bitergia.com>

### CODE REVIEW

**Comment by GeorgLink** [comment]
this pr fixes https://github.com/chaoss/grimoirelab/issues/217

Thank you @valeriocos for putting this together on such short notice!

**Comment by valeriocos** [comment]
you're welcome @GeorgLink ! we can discuss with @alpgarcia and the others the best visualization to show this data.

**Comment by GeorgLink** [comment]
@valeriocos I propose modifications to this PR: https://github.com/valeriocos/GrimoireELK/pull/1

**Comment by valeriocos** [comment]
sure, I have added a comment here: https://github.com/valeriocos/GrimoireELK/pull/1#pullrequestreview-293626744

**Comment by GeorgLink** [comment]
Woot woot ! you are a master of git :D and of course GrimoireLab

**Review by alpgarcia — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
