### PR TITLE
[setup.py] Add current dependency on perceval-opnfv

### PR DESCRIPTION
**Pull request by jgbarah**
The current version of perceval-opnfv is, AFAIK, 0.1.1.

### CODE REVIEW

**Review by acs — CHANGES_REQUESTED** [review]
@jgb I am not sure about this change. Could you recheck it with https://github.com/grimoirelab/perceval-opnfv/blob/master/setup.py#L47? Is this the version for the package?

**Comment by jgb** [comment]
@acs I'm afraid you're talking to the wrong guy (also in previous threads)

**Comment by jgbarah** [comment]
@jgb said:

> @acs I'm afraid you're talking to the wrong guy (also in previous threads)

Yes. I'm @jgbarah, @acs ;-)

**Comment by jgbarah** [comment]
@acs Yes, but see https://github.com/grimoirelab/perceval-opnfv/pull/2

If you want, I care of all of this as a part of the release of elasticgirl.18.1, and you can forget about it ;-)

**Comment by acs** [comment]
Yes @jgb go ahead with this kind of changes in versions for pip packages!

**Comment by jgbarah** [comment]
Done. Closing this one.

**Pull request closed without merging**
