### PR TITLE
[grimoire_elk] Goodbye track_items.py

### PR DESCRIPTION
**Pull request by valeriocos**
This code removes the track_items.py which has been replaced by the `filter-raw` feature.

### CODE REVIEW

**Comment by valeriocos** [comment]
@acs , it seems that this script is not used anymore. Do you remember what it was used for?
Can we delete it?

**Comment by valeriocos** [comment]
ping @acs

**Comment by valeriocos** [comment]
@sanacl @jgb do you know if this script is still useful?

**Comment by sduenas** [comment]
If nobody says other thing we can remove it

**Review by sduenas — APPROVED** [review]
LGTM

**Pull request merged**
