### PR TITLE
Fix gerrit enrich error for hyperledger sawtooth, fixes #739

### LINKED ISSUE #739: Gerrit backend: KeyError: 'owner'
User's SSH key is set in `~/.ssh/id_rsa`
`p2o.py --enrich --index sds-hyperledger-sawtooth-gerrit-raw --index-enrich sds-hyperledger-sawtooth-gerrit -e (redacted) --db-host mariadb.mariadb --db-sortinghat sortinghat --db-user sortinghat --db-password (redacted) gerrit gerrit.hyperledger.org --user (redacted) --disable-host-key-check --no-archive`:
```[gerrit] Incremental from: 2019-12-04 21:20:16+00:00 for gerrit.hyperledger.org
2019-12-05 06:07:38,816 Received 500 reviews in 5.89s
2019-12-05 06:07:38,830 [gerrit] Done collection for gerrit.hyperledger.org
2019-12-05 06:07:38,830 Backend feed completed
2019-12-05 06:07:43,791 Error enriching raw from gerrit (gerrit.hyperledger.org): 'owner'
Traceback (most recent call last):
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 657, in enrich_backend
    total_ids = load_identities(ocean_backend, enrich_backend)
  File "/repos/grimoirelab-elk/grimoire_elk/elk.py", line 415, in load_identities
    for identity in identities:
  File "/repos/grimoirelab-elk/grimoire_elk/enriched/gerrit.py", line 136, in get_identities
    user = item['owner']
KeyError: 'owner'
2019-12-05 06:07:43,794 [gerrit] Done enrichment for gerrit.hyperledger.org
2019-12-05 06:07:43,795 Enrich backend completed
2019-12-05 06:07:43,795 Finished in 0.18 min```

### PR DESCRIPTION
**Pull request by lukaszgryglicki**
Fixes #739 
Signed-off-by: Lukasz Gryglicki <lukaszgryglicki@o2.pl>

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
cc @valeriocos

**Comment by lukaszgryglicki** [comment]
Build failed for github2, this is totally unrelated to my changes IMHO and looks like build flake: https://travis-ci.org/chaoss/grimoirelab-elk/jobs/621612329?utm_medium=notification&utm_source=github_status

**Comment by valeriocos** [comment]
@lukaszgryglicki try to restart the travis job, the error should disappear.

I would like to test your code directly on that gerrit instance. I'll check how to get access to it.

**Comment by lukaszgryglicki** [comment]
You need a user and `id_rsa/id_rsa.pub` private/public keys, you need to add your own public key to the Gerrit, then you can use your private key + your username.
I don't see any option to restart the job:
Screenshot 2019-12-06 at 16 20 33
That fix was created after more than 5 trial and errors, that code finally synced Hyperledger's Sawtooth's Gerrit in my [sds](https://github.com/LF-Engineering/sync-data-sources) cron job.

**Comment by valeriocos** [comment]
> You need a user and id_rsa/id_rsa.pub private/public keys, you need to add your own public key to the Gerrit, then you can use your private key + your username.

ok

> I don't see any option to restart the job:

Probably it's due to limited permissions on this repo

> That fix was created after more than 5 trial and errors, that code finally synced Hyperledger's Sawtooth's Gerrit in my sds cron job.

ok

**Comment by lukaszgryglicki** [comment]
Any news?

**Comment by valeriocos** [comment]
I launched the collection phase some hours ago. Tomorrow I'll test your PR and ping you. Sorry for the late reactions but today is holidays in Madrid and Monday too.

**Comment by lukaszgryglicki** [comment]
OK, great, thanks.

**Comment by valeriocos** [comment]
@lukaszgryglicki I submitted another PR (https://github.com/chaoss/grimoirelab-elk/pull/742) since I wanted to check if I can restart the build (it seems I don't have enough permission either).

I kept you as author, since the code is basically the same. I have just replaced the if conditions with a more compacted version.

**Comment by lukaszgryglicki** [comment]
Sure, You can replace my PR with anything, I just want that error to be fixed, no matter who is the author.

**Comment by lukaszgryglicki** [comment]
Can we marge this (#741) or that (#742) this is quite important for us, we're trying to avoid maintaining patched versions, so we're trying to upstream all bugs and fixes.

**Pull request closed without merging**
